# Only one of the following two should be set to True
log_autoencoder_training: True
log_BCQ_training: False

# device: 'cuda'
device: 'cpu'
random_seed: 1234 # updated by run scripts
folder_location: './results/'
#  commented out because will be created based on hyperparameters
# folder_name: 'test' # updated by run scripts 
resume: False
minibatch_size: 128
drop_smaller_than_minibatch: True
sided_Q: 'negative'  #Can be 'positive' or 'negative'
perception_neg_traj_ratio: 'NA'

state_dim_gnn: 34
state_dim: 33                      
num_actions: 25   
context_dim: 5                     # Number of context/demographic/binary indicator variables we'll use as input

 
dem_context: True
bcq_num_nodes: 64 # as in the paper
# update these manually
storage_path: '/home/khakhtai/gnn-rl-sepsis/'

train_data_file: '/home/khakhtai/gnn-rl-sepsis/data/train_set_tuples'
validation_data_file: '/home/khakhtai/gnn-rl-sepsis/data/val_set_tuples'
test_data_file: '/home/khakhtai/gnn-rl-sepsis/data/test_set_tuples'

behav_policy_file_wDemo: '/home/khakhtai/gnn-rl-sepsis/results/BC_Cloning/BC_model.pt'
behav_policy_file: '/scratch/ssd001/home/tkillian/ml4h2020_srl/BehavCloning/BC_l1e-5_n64_w0_sgd/BC_model.pt'
