num_nodes: 128
hidden_size: 128 # num_nodes should be equal to hidden_size, it's the same but used in different places with different names

learning_rate: 0.0001
storage_folder: '/home/khakhtai/gnn-rl-sepsis/results/BC_Cloning/'
batch_size: 128
num_epochs: 5000
# num_epochs: 1
weight_decay: 0.1
optim_type: 'adam'


# files for the raw data saved to replay buffers
train_buffer: '/home/khakhtai/gnn-rl-sepsis/data/replay_buffer_without_encoding/train_buffer'
val_buffer: '/home/khakhtai/gnn-rl-sepsis/data/replay_buffer_without_encoding/val_buffer'
