autoencoder: 'GNN' 
            
context_input: True              

pol_learning_rate: 0.0001 
hidden_size: 64


# Autoencoder Hyperparameters

autoencoder_saving_period: 1 # Validation
inject_action_gnn: True
autoencoder_num_epochs: 1
autoencoder_lr: 0.001 
encoder_hidden_size: 64
encoder_num_layers: 2

# Not used
corr_coeff_param: 0   

