autoencoder: 'GNN' 
gnn_gentype: 2 # 1 or 2. 1 is SAGEConv; 2 is GATv2Conv
            
context_input: True              

pol_learning_rate: 0.001 
hidden_size: 64


# Autoencoder Hyperparameters

autoencoder_saving_period: 10 # Validation
inject_action_gnn: True
autoencoder_num_epochs: 200
# autoencoder_num_epochs: 1

autoencoder_lr: 0.001 
encoder_hidden_size: 64
encoder_num_layers: 1 #1 layers for gnn_gentype 2, 2 layers for gnn_gentype 1.

# Not used
corr_coeff_param: 0   

