    # parser.add_argument('--demographics', dest='dem_context', default=True, action='store_true')
    # parser.add_argument('--num_nodes', dest='num_nodes', default=128, type=int)
    # parser.add_argument('--learning_rate', dest='learning_rate', default=1e-4, type=float)
    # parser.add_argument('--storage_folder', dest='storage_folder', default='test', type=str)
    # parser.add_argument('--batch_size', dest='batch_size', default=128, type=int)
    # parser.add_argument('--num_epochs', dest='num_epochs', default=5000, type=int)
    # parser.add_argument('--weight_decay', dest='weight_decay', default=0.1, type=float)
    # parser.add_argument('--optimizer_type', dest='optim_type', default='adam', type=str)


# num_nodes: 128
hidden_size: 128 # num_nodes
learning_rate: 0.0001
storage_folder: 'test'
batch_size: 128
num_epochs: 5000
weight_decay: 0.1
optim_type: 'adam'
device: 'cpu' # 'cuda'

# files for the raw data saved to replay buffers
train_buffer_file: '/Users/taiskha/Master Thesis/code/data/replay_buffer_without_encoding/train_buffer'
val_buffer_file: '/Users/taiskha/Master Thesis/code/data/replay_buffer_without_encoding/val_buffer'

# place where behavior cloning models are saved
storage_dir: '/Users/taiskha/Master Thesis/code/rl_representations-main/output/BehavCloning/'
